# ===============================
# Server Configuration
# ===============================
server.port=${SERVER_PORT:8081}

# ===============================
# MongoDB Configuration
# ===============================
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/cloudhosting}

# ===============================
# File Upload Configuration
# ===============================
file.upload-dir=${UPLOAD_DIR:C:/Users/PATHANIA/Desktop/Deployersfinal/uploads/}
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# ===============================
# Logging Configuration
# ===============================
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=DEBUG

# ===============================
# Actuator Configuration (For Monitoring)
# ===============================
management.endpoints.web.exposure.include=*
# Tomcat-specific connection settings
server.tomcat.max-swallow-size=500MB
server.tomcat.max-http-post-size=500MB
server.undertow.max-http-post-size=500MB






